// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ScrapLinkedInDall.Database.Models;

[Table("Education")]
public partial class Education
{
    [Key]
    public int EducationId { get; set; }

    [Required]
    public string Details { get; set; }

    public int UserProfileId { get; set; }

    [ForeignKey("UserProfileId")]
    [InverseProperty("Educations")]
    public virtual UserProfile UserProfile { get; set; }
}