// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ScrapLinkedInDall.Database.Models;

[Table("UserProfile")]
public partial class UserProfile
{
    [Key]
    public int UserProfileId { get; set; }

    [Required]
    [StringLength(200)]
    public string Name { get; set; }

    [Required]
    [StringLength(500)]
    public string Headline { get; set; }

    [Required]
    [StringLength(200)]
    public string Location { get; set; }

    [InverseProperty("UserProfile")]
    public virtual ICollection<Education> Educations { get; set; } = new List<Education>();

    [InverseProperty("UserProfile")]
    public virtual ICollection<Experience> Experiences { get; set; } = new List<Experience>();

    [InverseProperty("UserProfile")]
    public virtual ICollection<LicenseCertification> LicenseCertifications { get; set; } = new List<LicenseCertification>();
}